rm -rf lib/trinitycrdriver/trinitycrdriver.so
rm -rf rake_test_opt_chease_defaults.rb
rm -rf rake_test_opt_defaults.rb
rm -rf test/chease_opt/.CODE_RUNNER_TEMP_RUN_LIST_CACHE
rm -rf test/chease_opt/ogyropsi.dat
rm -rf test/chease_opt/v/
rm -rf test/chease_opt_chease/.CODE_RUNNER_TEMP_RUN_LIST_CACHE
rm -rf test/chease_opt_chease/v/
rm -rf test/trinopt/
